### ISSUE TITLE
ldap anonymous binding

### ISSUE THREAD

**Issue by mestia** [xperseguers/t3ext-ig_ldap_sso_auth#124]
Should anonymous bind work or is it required to have an "admin" binddn? The anonymous binding used to work in the older versions of typo3 and this plugin.
After setting up the plugin  the authentication for both frontend and backend users is "disabled", but I can search and import users and groups.
Any hint on how to enable the authentication? 

Thank you,
Alex

**Comment by xperseguers** [comment]
Since Active Directory is forcing to use an authenticated user for performing searches (unless you start hacking the registry which is something most administrators won't do), we did not check for anonymous binding. But you don't need any "admin" binddn, you only need some basic read-only binddn.

HTH.

If you feel like anonymous binding would be easy to implement and works for you, feel free to reopen and link a PR.
