### ISSUE TITLE
Backend LDAP users with admin-flag can't access admin-modules with user password

### ISSUE THREAD

**Issue by jkkauhan** [xperseguers/t3ext-ig_ldap_sso_auth#148]
We are authenticating backend users with ig_ldap_sso_auth and some users have their admin-flag set. When trying to access admin modules in the backend, TYPO3 v10 requests the user password again for extra security. LDAP authenticated users get message that their password is not correct, where local TYPO3 users get access to admin modules. Workaround is to use install tool password.

**Comment by pi-phi** [comment]
Confirmation for TYPO3 11.5.35 and ig_ldap_sso_auth 3.7.1.
in the log I can find:
`Login-attempt from 10.100.123.123, username 'pi_phi', no suitable hash method found! `

**Comment by tylkomat** [comment]
The reason is that the configuration is not initialized. This is usually done in [getUser](https://github.com/xperseguers/t3ext-ig_ldap_sso_auth/blob/master/Classes/Service/AuthenticationService.php#L77), but in case of admin modules like Setting, Maintenance or Upgrade, only [authUser](https://github.com/xperseguers/t3ext-ig_ldap_sso_auth/blob/master/Classes/Service/AuthenticationService.php#L219) gets called, because the user is already stored in the session. There is a [check](https://github.com/xperseguers/t3ext-ig_ldap_sso_auth/blob/master/Classes/Service/AuthenticationService.php#L221) which should at least allow local users to authenticate, but that check never fails. [isInitialized](https://github.com/xperseguers/t3ext-ig_ldap_sso_auth/blob/master/Classes/Library/Configuration.php#L150) checks for `$mode` not beeing `null`, but the [default value](https://github.com/xperseguers/t3ext-ig_ldap_sso_auth/blob/master/Classes/Library/Configuration.php#L46) of that variable is `be`.

**Comment by xperseguers** [comment]
Please check PR
