### ISSUE TITLE
Backend user First log in message for Authorization - 3.7.1

### ISSUE THREAD

**Issue by ArchonSlime** [xperseguers/t3ext-ig_ldap_sso_auth#160]
Hello,

I don't know if this is the intended behaviour, but when a user first tries to login in the backend, it creates the user disable (wich is what we want) but the user doesn't have any feedback on what is happening, they just get redirected to the login page with no message.

So I was wondering if a message was supposed to be shown like or if it could be added. Something like "Please contact your administrator for your account to be authorized."

Thank you!

**Comment by xperseguers** [comment]
Did you follow the suggested configuration ? https://docs.typo3.org/p/causal/ig_ldap_sso_auth/3.7/en-us/AdministratorManual/SampleConfiguration.html#be-users

**Comment by xperseguers** [comment]
The `disabled` mapping was added as part of #44

**Comment by ArchonSlime** [comment]
Hello, we were not using the suggested configuration, thanks for the heads-up. We decided to use them and not do a double opt-in for the backend user.

I do still think it could be interesting to have a message for the backend user in case the automatic enabling isn't the wanted behavior.

Thank you!

**Comment by xperseguers** [comment]
Disabled by default (normally on creation from within the Backend) is a new default since TYPO3 v10 (or v11?), so unrelated to this extension.

I agree that double-opt in with message could be useful, but this is considered out of scope for this extension and should better implemented by a custom extension by hooking into this extension and reacting upon user creation/... to fit your business use case the exact way you expect it.
