### ISSUE TITLE
Lock wait timeout on fe_users during synchronise

### ISSUE THREAD

**Issue by klodeckl** [xperseguers/t3ext-ig_ldap_sso_auth#167]
Hello,

everytime when the scheduler task runs and synchronises fe_users I get error messages when somebody wants to login: 
Lock wait timeout exceeded; try restarting transaction | Doctrine\DBAL\Exception\LockWaitTimeoutException thrown in file /var/www/typo3/typo3_src-10.4.36/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php in line 54.

It tries to make an update on fe_users.
Any idea how to fix this?

**Comment by klodeckl** [comment]
Push :)

**Comment by xperseguers** [comment]
You may need to increase a setting in your database server:

```sql
set innodb_lock_wait_timeout=100;
```

If this helps and you find a proper value based on some number of users you have, please drop a note so that it may be added to the official documentation as a hint.

**Comment by klodeckl** [comment]
I have innodb_lock_wait_timeout already set to 200.
I am currently working on the update to TYPO3 12. After the update I will test branch feature/symfony-command and check if it helps and report it here..

**Comment by xperseguers** [comment]
You will have to test official release (or master branch) as it's been officially published for TYPO3 v12 in the mean time :)

**Comment by klodeckl** [comment]
Ah ok, thanks for the information. I will switch back to the official release.

**Comment by xperseguers** [comment]
hard to tell why it sent from 30 to 45 minutes, although it looks like the generation of a random password for imported users is a culprit for taking "some time" in my latest tests. Possibly not the only one, but at least takes a non-negligible time. You could try to hardcode a fixed random password just to see if you go down to about 30-45 min... Which would mean there's possibly something to enhance or rework the server configuration so that randomness is quicker to get.

I figured out as well that in the current master there's a lot of connect/disconnect to the LDAP server, I coded a new "shared pool of LDAP connections" as https://github.com/xperseguers/t3ext-ig_ldap_sso_auth/pull/223 it looks like there's no side-effect but further tests would be good. But unfortunately it does not seem to be (really) related to the speed of the import.

**Comment by klodeckl** [comment]
Ok, I will check. Where can I find the password generation code?

**Comment by xperseguers** [comment]
https://github.com/search?q=repo%3Axperseguers%2Ft3ext-ig_ldap_sso_auth%20password&type=code

and look for random

**Comment by klodeckl** [comment]
Thanks a lot, it helped:

After I changed
`$password = $cryptoService->generateRandomBytes(20);`
to 
`$password = '34bcc2b1ec5ba9b5a71d5617023eb12e';`

the task was done in 8 minutes!!! :)

Why is there a need for a time and cpu intensive function to just generate a dummy value for the password?

**Comment by xperseguers** [comment]
Thanks @klodeckl, further discussion on that topic in #224.

If, as such, there's no (other) problem anymore with the lock wait timeout, I suggest we close that ticket in favour of the other one.

**Comment by klodeckl** [comment]
I just made a test again: During synchronizing I made several fe logins. I myself did not get an error, but first login took a long time (other logins after were fast). But in the TYPO3 logs I found six lock wait timeouts. So lets say: the problem still exists but is not that important anymore if the sync takes shorter than 10 minutes (and task is scheduled at night).

**Comment by xperseguers** [comment]
I don't see a solution for preventing locks during the transaction associated to an import.

Since version 4.0.0 (and changes in master branch), the scope and duration of the lock during the import has been minimized/shortened as much as possible.

There is still the ongoing discussion in #224 to allow making the import much quicker, but basically I don't see how lock could be minimized even more.

If you see something (else) to do, please comment, otherwise, I sadly don't see any other way and we will have to live with those inherent locks caused by the need for transaction(s) during the import. And as such, your only meaningful way will be to run your import either less often (you probably don't need to synchronize 1000's of LDAP accounts each and every day, since synchronization is performed during actual authentication as well), you can certainly find a time slot that hurt as little as possible any "very early bird". You could combine the import with a TYPO3 lock to make it clear authentication is temporarily unavailable, etc.

But this all seems to be out-of-scope of this extension and more something to be tackled with in the context of a given project/implementation.
