### ISSUE TITLE
disable mapping not working anymore

### ISSUE THREAD

**Issue by klodeckl** [xperseguers/t3ext-ig_ldap_sso_auth#181]
Hello! The mapping of the field disable doesn’t work anymore:

`disable = <loginDisabled>`
`disable.replacement.10 {`
`    search = TRUE`
`    replace = 1`
`}`

Commenting the following lines (240 and 248) in Classes/Utility/UserImportUtility.php lets it work again:
`$user[$GLOBALS['TCA'][$this->userTable]['ctrl']['enablecolumns']['disabled']] = 0;`

(The regular way of disabling a user doesn’t work in my case (Microfocus eDirectory is used).)

TYPO3 11 (in TYPO3 10 it worked without modifications), ig_ldap_sso_auth 3.7.1 and 3.8dev. PHP 8.2.

**Comment by xperseguers** [comment]
That seems a bit tricky to handle automatically as the mapping is done in one place and then the "restore" configuration of the extension is taken into account to see what to do with the hidden/disabled flag.

We would possibly to reapply the mapping at the very end, which sounds a bit overkill.

What I would prefer is sending a PSR-14 event for new and updated users, before they are actually persisted to database to let some edge-cases be taken into account.

That would be a bit similar to handling of the existing hook `extraDataProcessing` which could already be used to bit your need but somehow in a cleaner and more modern way.

**Comment by xperseguers** [comment]
Actually, and after double-checking, the PSR-14 event is already sent. Please listen and react to `UserUpdatedEvent` and/or `UserAddedEvent` to handle your specific need. Thanks.

**Comment by klodeckl** [comment]
I just want to have users disabled if the user is disabled (LDAP field loginDisabled) on the LDAP server. This only worked with the change mentioned above. I think this is not a special need, is it? Or am I just missunderstanding something? Thanks for your help!

**Comment by xperseguers** [comment]
I can see the need, the problem is that those hidden/disabled/deleted fields are indeed special fields used by the scheduler job to automatically disable/delete/do nothing formerly imported records based on latest status of the LDAP server.

I still don't get the exact purpose of trying to map the `loginDisabled` field from LDAP to TYPO3 though. Logically if some person has their `loginDisabled` field set to true in LDAP, then the account is disabled and not to be considered, right? You never want to do some weird business logic if that field is true but it's full moon and the person's family name starts with a B or S then it should be enabled nevertheless?

So why trying to map that field in the first place? It sounds like you just want to have an extended filter clause where that field **must be false** in order for a LDAP account to be considered. Filtering on that field, in addition to anything else, will effectively allow you to forbid access to TYPO3 to those disabled accounts, and allow you to revoke access through the scheduler task if an existing former account got locked out.

Or am I missing something?

**Comment by klodeckl** [comment]
The scheduler job does not disable accounts for ldap disabled accounts without the modification. I can see “Handling of missing users” and “Handling of restored users” in the scheduler job, but no “Handling of deactivated users”. I need to have them deactivated on both sides to query only active accounts for mailings and other things. It seems that this case was never considered but worked before years ago when mapping the fields. How about an option to synchronize the enabled/disabled state? (or an extension config option to let allow mapping of the field.) Would be great!

**Comment by xperseguers** [comment]
What about using such a filter for your Frontend users?

**Currently** you have something like that I guess:

```
(uid={USERNAME})
```

If you change it to:

```
(&(uid={USERNAME})(loginDisabled=0))
```

(or similar) this should do exactly what you want.

**Comment by klodeckl** [comment]
But then I could not differentiate between disabled and deleted accounts on the ldap server. I want to delete fe_users which are not present in ldap anymore otherwise I would have thousands of accounts disabled which are not existing anymore. I have configured “Handling of missing users“ = Delete.

**Comment by xperseguers** [comment]
Please test suggested PR

**Comment by xperseguers** [comment]
> It seems that this case was never considered but worked before years ago when mapping the fields.

Just so that it's clear why it changed... at some point (TYPO3 v10 or possibly v11 I don't remember without blaming the code), newly-created users where not usable right away as the default for new records was to mark them as hidden/disabled until manually enabled. This lead to users created automatically upon successful authentication to not being able to actually log into TYPO3. This didn't exist in former versions of TYPO3. This forced me to adapt the code and fiddle with the `disable` column...

**Comment by klodeckl** [comment]
I just tested with branch dev-bugfix/181-mapping-disable (on TYPO3 11.5.41). Seems to be working fine in my case. Thanks a lot! :)
