### ISSUE TITLE
Import sets all new imported be_user disabled

### ISSUE THREAD

**Issue by jmcclane** [xperseguers/t3ext-ig_ldap_sso_auth#44]
Can anyone help me out on this? W/ a new empty be_user table all imported be_users are disabled.

**Comment by chrosey** [comment]
this is due an security patch in typo3 core.
we got the same problem for every new user. 

Is there an possibility to overwrite default disabled state?

**Comment by pi-phi** [comment]
That is caused by the last security update of TYPO3.
Since then all `*_users` records have the field `disabled` set to true by default. 

As workaround you can modify the TCA of `*_users.disabled`:

in `ext:mysiteconfig/Configuration/TCA/Overrides/be_users.php` have a line: 

    $GLOBALS['TCA']['be_users']['columns']['disable']['config']['default'] = 0;

the same for `fe_users`.

**note**: changes in `ext_tables.sql` have no effect.

----

As creating enabled users on the fly can be seen as security hole, but activating a lot of users which are handled in an AD could be very much work, it should be configurable whether new records are enabled or disabled. I would like to see a configuration in `ig_ldap_sso_auth` to enable automatic created `*_users` on automatic creation. (default might be: new users are disabled.)

**Comment by xperseguers** [comment]
Do you have a link to the security change in Core?

**Comment by pi-phi** [comment]
https://review.typo3.org/#/c/59521/ line 182

**Comment by xperseguers** [comment]
Fixed by suggestion in https://github.com/xperseguers/t3ext-ig_ldap_sso_auth/commit/4525e06dea5abd6264d19f257cb902be253d24df
