### ISSUE TITLE
Clarify PHP compatibility

### ISSUE THREAD

**Issue by felixbuenemann** [xperseguers/t3ext-ig_ldap_sso_auth#76]
The extension version 3.4.0 currently lists a requirement of PHP 7.2+, but TYPO3 8.7 requires PHP 7.0+.

Since the extensions seems to work fine on at least PHP 7.1, shouldn't the PHP requirement be dropped to 7.0+ to match TYPO3 v8.7?

**Comment by xperseguers** [comment]
Sure, if it works, I usually did such requirement if I started to use PHP 7.2 features. For that specific case, I honestly don't remember if I actually used PHP 7.2 features or if I considered that PHP < 7.2 was EOL and I would not check if code worked with former versions.

**Comment by xperseguers** [comment]
PHP 7.0 is for sure not supported anymore since I found a few usages of nullable types introduced in PHP 7.1. I'm not sure PHP 7.2 is a hard requirement but support for 7.1 is soon ended (security-wise, see https://www.php.net/supported-versions.php). I don't think we need to change back to PHP 7.1 and change again in a few months, if you really need to have it running on PHP 7.1 and you know it works anyway, then ignore the PHP version requirement and run it at your own risk.
